version: '3'

services:
  node:
    build: .
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/bussr
    links:
      - mongo
    ports:
      - 3000:3000
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
