version: '3'

services:
  node:
    build: .
    restart: always
    links:
      - mongo
    ports:
      - 80:3000
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
