version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: always
    links:
      - mongo
    ports:
      - 80:3000
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
